### ISSUE TITLE
Send Graphics to Paul

### ISSUE THREAD

**Issue by iLevyTate** [xyvora/achievaim#102]
Upscale images before sending

**Comment by iLevyTate** [comment]
- ![AchieveAim Profile (Identicon) Picture - 500 x 500 (1)](https://github.com/xyvora/achievaim/assets/78818969/7c7d6eec-22f7-4327-8c32-8f62d3fe86be)
- ![AchieveAim Profile Picture - 1280 x 640](https://github.com/xyvora/achievaim/assets/78818969/6a4b7533-e916-4643-8738-eaeb4dfe639c)
- ![Xyvora Profile Social Media Picture - 1280 X 640](https://github.com/xyvora/achievaim/assets/78818969/858240cf-979b-4ce6-a01f-3b933920c7ba)
- ![Untitled Project (3)](https://github.com/xyvora/achievaim/assets/78818969/ce6cdc72-6ecc-4332-9484-74fda07395a1)

**Comment by iLevyTate** [comment]
@sanders41 

These are the graphics generated for both the org. and repo. so you can use this for the Discord server as well.

**Comment by sanders41** [comment]
Done
