### ISSUE TITLE
Add branch protection rules

### ISSUE THREAD

**Issue by sanders41** [xyvora/achievaim#30]
We should add branch protection rules for PRs

**Comment by iLevyTate** [comment]
I thought there was already branch protection for main. I know I set the basic default for the main, but I may need to change the specific settings.

**Comment by sanders41** [comment]
I'm specifically referring to the rules that require the tests to pass before merging.

**Comment by iLevyTate** [comment]
Okay. Do you have access to make those modifications? I know you're a collaborator on the project and I tried to give you the same permission but I'm not sure. If you do, Let me know. If not let me know so I can get that set up correctly.

**Comment by sanders41** [comment]
I looked but don't have access. I may be wrong, but I don't think it is possible to give that level of access for other users to a repo in a personal account.

**Comment by sanders41** [comment]
This has been setup now.
