### ISSUE TITLE
Potentially change repo. name that will align with App name. Current repo name is less than optimal. 

### ISSUE THREAD

**Issue by iLevyTate** [xyvora/achievaim#46]
Potential names for repo change before unofficially publicized. 

1. [x] "AImarkableTargets"
2. [x] "GoalGetterAI"
3. [ ] ~"SMARTGenie"~
4. [x] "TrackAI"
5. [x] "AImpactGoals"
6. [ ] ~"MeasurAble"~
7. [ ] ~"SMARTSyncAI"~
8. [x] "RelativAI"
9. [x] "TimeBoundAI"
10. [ ] ~"OptimAIm"~
11. [ ] ~"GenSMART"~
12. [x] "GaugeGoalsAI"
13. [x] "AImbitiousPath"
14. [x] "AImReach"
15. [x] "SMARTSprintAI"
16. [x] "AchievAIm"
17. [x] "GoalGraphAI"
18. [ ] ~"AIspire"~
19. [ ] ~"TrackerAI"~
20. [x] "SMARTSpectraAI".
21. [x] "SMARTGoalGenAI"
22. [ ] ~"AIchieveSMART"~
23. [ ] ~"SMARTTrackAI"~
24. [ ] ~"GoalGaugeSMART"~
25. [ ] ~"SMARTSpectrumAI"~
26. [x] "GenAISmartGoals"
27. [x] "SMARTMilestoneAI"
28. [x] "SMARTSpireAI"
29. [x] "AiSMARTProgress"
30. [ ] ~"GoalGatherSMART"~
31. [x] "AISmartPath"
32. [x] "SMARTVistaAI"
33. [x] "SmartMoverAI"
34. [ ] ~"GoalGridSMART"~
36. [ ] ~"SmartStepAI"~
37. [ ] ~"SMARTSculptAI"~
38. [ ] ~"GoalGuideSMART"~
39. [x] "SMARTFrontierAI"
40. [ ] ~"AIMappedSMART"~

**Comment by sanders41** [comment]
For the repo name itself we should go with all lower case and kabab case. So if the name of the project is SMARTGoalPT, the repo name should be smart-goal-pt, or smartgoalpt, or whatever makes sense. It makes things easier to work with this way. The app name can still be SMARTGoalPT (or whatever is decided).

**Comment by iLevyTate** [comment]
Okay. Do you have a preference from the list above?

**Comment by sanders41** [comment]
It would probably be worth it to see what domain names are available from the list and that could narrow it down. I haven't had a chance to do that yet.

**Comment by sanders41** [comment]
I went through and checked domain names. For now I only looked at .com

:white_check_mark: = available
~strike through~ = not available

**Comment by iLevyTate** [comment]
Selected achievaim as name.
